POST http://localhost:4000/v1/register
Content-Type: application/json

{
 "user_name": "testUser1",
 "user_email": "testUser1@gmail.com",
 "password": "testUser1",
 "is_admin": false
}

###register
GET http://localhost:4000/v1/register
Content-Type: application/json

### login
POST http://localhost:4000/v1/login
Content-Type: application/json

{
 "user_name": "testUser1",
 "password": "testUser12"
}

### login get
GET http://localhost:4000/v1/login
Content-Type: application/json